#!/usr/bin/env python3
"""Materialise a power-limit variant of the publication optimization config.

The constant-power base pins ``battery.max_charge_power_w`` and leaves discharge
unbounded. A C-rate variant removes both absolute limits and sets
``battery.power_limit_c_rate``, which derives a symmetric charge and discharge
limit from each candidate's capacity.
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(PROJECT_ROOT))

BASE = PROJECT_ROOT / "validation/article1/article1-projected-optimization.toml"
DROP = ("max_charge_power_w", "max_discharge_power_w")
BANNER = """# GENERATED by tools/revision/make_power_variant_config.py — do not hand-edit.
# Base: validation/article1/article1-projected-optimization.toml
# Base sha256: {base_sha}
# Change: drop the absolute battery power limits; apply a symmetric
#         capacity-proportional limit of {rate} C to charge and discharge.
# Product basis: BYD Battery-Box Premium HVS (LFP), datasheet V1.7 EN. Every
#   HVS size is rated 25 A max output current against a nominal voltage that
#   scales with module count -- 5.12 kWh at 204.8 V, 7.68 kWh at 307.2 V,
#   10.24 kWh at 409.6 V, 12.8 kWh at 512 V -- i.e. exactly 1.00 C continuous
#   across the whole family. The HVM family is 50 A at half the voltage per
#   module, giving 0.93 C. Peak is 50 A for 3 s (2 C).
"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--c-rate", type=float, required=True)
    ap.add_argument("--output", type=Path, required=True)
    args = ap.parse_args()

    raw = BASE.read_bytes()
    base_sha = hashlib.sha256(raw).hexdigest()
    lines = raw.decode("utf-8").splitlines()

    out: list[str] = []
    in_battery = False
    injected = False
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("["):
            if in_battery and not injected:
                out.append(f"power_limit_c_rate = {args.c_rate}")
                out.append("")
                injected = True
            in_battery = stripped == "[battery]"
        if in_battery and any(stripped.startswith(f"{k} =") for k in DROP):
            out.append(f"# removed by the {args.c_rate} C variant: {stripped}")
            continue
        out.append(line)
    if in_battery and not injected:
        out.append(f"power_limit_c_rate = {args.c_rate}")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(BANNER.format(base_sha=base_sha, rate=args.c_rate) + "\n".join(out) + "\n")
    print(f"Wrote {args.output}")
    print(f"  base sha256    {base_sha}")
    print(f"  variant sha256 {hashlib.sha256(args.output.read_bytes()).hexdigest()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
