#!/usr/bin/env python3
"""Compare BREOS results against the external references.

Reads ``validation/results/breos_results.json`` (falling back to the
committed baseline) and the reference JSONs, prints a comparison table, and
writes ``validation/REPORT.md``.

The references do NOT share weather with BREOS: BREOS runs on a PVGIS TMY,
PVGIS PVcalc averages the full multi-year satellite record, and PVWatts uses
NSRDB/international station data. Deviations therefore bundle weather-source
differences with model differences — expect single-digit percentages, and
read the monthly shape, not just the annual number.

Usage:
    uv run python validation/compare.py
"""

import datetime
import json
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from validation.common import (  # noqa: E402
    BASELINE_PATH,
    MONTH_LABELS,
    REPORT_PATH,
    RESULTS_PATH,
    load_reference,
    load_spec,
)


def _pct(value: float, reference: float):
    if not reference:
        return None
    return (value / reference - 1.0) * 100.0


def _fmt_pct(p):
    return f"{p:+.1f}%" if p is not None else "—"


def _fmt_kwh(v):
    return f"{v:.0f}" if v is not None else "—"


def build_rows(results: dict):
    rows = []
    for key, res in results["locations"].items():
        ref = load_reference(key) or {}
        pvgis = ref.get("pvgis_pvcalc") or {}
        pvwatts = ref.get("pvwatts_v8") or {}

        iso = res["models"]["isotropic"]["annual_kwh"]
        perez = res["models"]["perez"]["annual_kwh"]
        perez_mid = (res["models"].get("perez_mid") or {}).get("annual_kwh")
        perez_diffuse = (res["models"].get("perez_diffuse") or {}).get("annual_kwh")
        pvgis_annual = pvgis.get("annual_kwh")
        pvwatts_annual = pvwatts.get("annual_kwh")

        monthly_dev_max = None
        if pvgis.get("monthly_kwh"):
            devs = [_pct(b, r) for b, r in zip(res["models"]["perez"]["monthly_kwh"], pvgis["monthly_kwh"]) if r]
            if devs:
                monthly_dev_max = max(devs, key=abs)

        notes = []
        if pvgis:
            notes.append(f"PVGIS {pvgis.get('radiation_db', '?')} {pvgis.get('years', '?')}")
        if pvwatts.get("error"):
            notes.append("PVWatts: fetch failed")
        elif pvwatts:
            dist = pvwatts.get("station_distance_m")
            notes.append(f"PVWatts {pvwatts.get('dataset')} ({dist} m){'' if pvwatts.get('trusted') else ' UNTRUSTED'}")

        rows.append(
            {
                "key": key,
                "name": ref.get("name", key),
                "iso": iso,
                "perez": perez,
                "perez_mid": perez_mid,
                "perez_diffuse": perez_diffuse,
                "pvgis": pvgis_annual,
                "pvgis_dev": _pct(perez, pvgis_annual),
                "pvgis_dev_iso": _pct(iso, pvgis_annual),
                "pvgis_dev_mid": _pct(perez_mid, pvgis_annual) if perez_mid is not None else None,
                "pvgis_dev_diffuse": _pct(perez_diffuse, pvgis_annual) if perez_diffuse is not None else None,
                "pvwatts": pvwatts_annual,
                "pvwatts_dev": _pct(perez, pvwatts_annual),
                "monthly_dev_max": monthly_dev_max,
                "notes": "; ".join(notes),
                "monthly_breos": res["models"]["perez"]["monthly_kwh"],
                "monthly_pvgis": pvgis.get("monthly_kwh"),
            }
        )
    return rows


def print_table(rows, results):
    print(f"\nBREOS {results['breos_version']} validation — annual AC yield (kWh), 4 kWp system")
    header = (
        f"{'location':<16} {'BREOS iso':>10} {'BREOS perez':>12} {'perez+mid':>10} {'perez+diam':>10} {'PVGIS':>8} "
        f"{'Δperez':>8} {'Δ+mid':>8} {'Δ+diam':>8} {'Δiso':>8} {'PVWatts':>8} {'Δperez':>8}  notes"
    )
    print(header)
    print("-" * len(header))
    for r in rows:
        print(
            f"{r['key']:<16} {r['iso']:>10.0f} {r['perez']:>12.0f} {_fmt_kwh(r['perez_mid']):>10} "
            f"{_fmt_kwh(r['perez_diffuse']):>10} {_fmt_kwh(r['pvgis']):>8} "
            f"{_fmt_pct(r['pvgis_dev']):>8} {_fmt_pct(r['pvgis_dev_mid']):>8} "
            f"{_fmt_pct(r['pvgis_dev_diffuse']):>8} {_fmt_pct(r['pvgis_dev_iso']):>8} "
            f"{_fmt_kwh(r['pvwatts']):>8} {_fmt_pct(r['pvwatts_dev']):>8}  {r['notes']}"
        )


def write_report(rows, results):
    system, _ = load_spec()
    lines = [
        "# BREOS validation report",
        "",
        f"Generated by `validation/compare.py` on {datetime.date.today().isoformat()} "
        f"against BREOS {results['breos_version']}.",
        "",
        f"System: {system['peak_power_kw']} kWp ({system['n_modules']}× {system['module']}), "
        f"DC/AC {system['dc_ac_ratio']}, inverter η {system['inverter_efficiency']:.2f}, "
        f"albedo {system['albedo']}, free-standing mount, BREOS default loss stack.",
        "",
        "Deviations bundle weather-source differences with model differences "
        "(BREOS runs on a PVGIS TMY; PVGIS PVcalc averages the full multi-year record; "
        "PVWatts uses NSRDB/international station data). The tight regression guarantee "
        "is the baseline test in `tests/test_validation_drift.py`; these bands catch gross drift.",
        "",
        "## Annual AC yield (kWh)",
        "",
        "| Location | BREOS isotropic | BREOS perez | BREOS perez+mid-interval | BREOS perez+diffuse-IAM "
        "| PVGIS PVcalc | Δ perez vs PVGIS | Δ perez+mid vs PVGIS | Δ perez+diffuse vs PVGIS "
        "| PVWatts v8 | Δ perez vs PVWatts | Notes |",
        "|---|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    for r in rows:
        lines.append(
            f"| {r['name']} | {r['iso']:.0f} | {r['perez']:.0f} | {_fmt_kwh(r['perez_mid'])} "
            f"| {_fmt_kwh(r['perez_diffuse'])} "
            f"| {_fmt_kwh(r['pvgis'])} | {_fmt_pct(r['pvgis_dev'])} | {_fmt_pct(r['pvgis_dev_mid'])} "
            f"| {_fmt_pct(r['pvgis_dev_diffuse'])} "
            f"| {_fmt_kwh(r['pvwatts'])} | {_fmt_pct(r['pvwatts_dev'])} "
            f"| {r['notes']} |"
        )

    lines += ["", "## Monthly shape vs PVGIS (BREOS perez, kWh)", ""]
    for r in rows:
        if not r["monthly_pvgis"]:
            continue
        lines.append(f"### {r['name']}")
        lines.append("")
        lines.append("| | " + " | ".join(MONTH_LABELS) + " |")
        lines.append("|---|" + "---|" * 12)
        lines.append("| BREOS | " + " | ".join(f"{v:.0f}" for v in r["monthly_breos"]) + " |")
        lines.append("| PVGIS | " + " | ".join(f"{v:.0f}" for v in r["monthly_pvgis"]) + " |")
        devs = [_fmt_pct(_pct(b, p)) for b, p in zip(r["monthly_breos"], r["monthly_pvgis"])]
        lines.append("| Δ | " + " | ".join(devs) + " |")
        lines.append("")

    REPORT_PATH.write_text("\n".join(lines) + "\n")
    print(f"\nWrote {REPORT_PATH.relative_to(PROJECT_ROOT)}")


def main():
    results_path = RESULTS_PATH if RESULTS_PATH.exists() else BASELINE_PATH
    if not Path(results_path).exists():
        print("No BREOS results found. Run validation/run_breos.py first.")
        sys.exit(1)
    with open(results_path) as f:
        results = json.load(f)

    rows = build_rows(results)
    if not rows:
        print("No locations to compare.")
        sys.exit(1)

    print_table(rows, results)
    write_report(rows, results)


if __name__ == "__main__":
    main()
