"""Generate docs/getting-started/config-reference.md from the config registry.

Every top-level App key comes from ``breos.app_config.APP_CONFIG_FIELDS`` and
every nested-table key from the ``TableSpec`` that validates it, so the page
lists exactly the keys BREOS accepts, with their defaults, CLI flags and
allowed values. The descriptions are the registry's ``doc`` text; a key
without one fails the generator.

Regenerate after changing the registry:

    uv run python tools/generate_config_docs.py

CI runs this with ``--check`` and fails when the committed page is stale.
"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import fields
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from breos import app_config  # noqa: E402
from breos.app_config import (  # noqa: E402
    APP_CONFIG_FIELDS,
    COSTS_TABLE,
    INDOOR_MODEL_TABLE,
    NESTED_TABLE_SPECS,
    PERIOD_TABLE,
    PV_ARRAY_TABLE,
    REFERENCE_TARIFF_TABLE,
    SMART_CHARGING_TABLE,
    TARIFF_TABLE,
    TERMINAL_VALUE_TABLE,
)
from breos.config_schema import TableSpec  # noqa: E402
from breos.economics import COST_CONFIG_KEY_TO_PARAM, CostParams  # noqa: E402

OUTPUT_PATH = REPO_ROOT / "docs" / "getting-started" / "config-reference.md"

HEADER = """\
<!-- Generated by tools/generate_config_docs.py. Do not edit by hand. -->

# Configuration key reference

Every key a {py:class}`~breos.App` config accepts, generated from the
configuration registry that validates it. A key that is not listed here is
rejected. The keys inside the `[montecarlo]` and `[sweep]` runner sections are
described on the [Monte Carlo](monte-carlo.md) and
[Run a parameter sweep](../how-to/parameter-sweep.md) pages. [Configuration](configuration.md) explains how the keys work
together; [Packaged options](options.md) lists the preset keys they accept.
"""

TOP_LEVEL_INTRO = """\
The top level of a config dict or TOML file. A CLI flag, where there is one,
is a `breos run` option that overrides the config file.
"""

# Nested tables in page order: the heading, the spec, and the introduction.
TABLES: tuple[tuple[str, TableSpec, str], ...] = (
    (
        "costs",
        COSTS_TABLE,
        "Cost overrides, as `[costs]` in TOML. A key you omit comes from `cost_preset`, and without a preset from "
        "the {py:class}`~breos.economics.CostParams` default shown. Values are in the cost preset's currency and must be "
        "finite and not negative.",
    ),
    (
        "battery_indoor_model",
        INDOOR_MODEL_TABLE,
        "The indoor-buffering model, as `[battery_indoor_model]` in TOML. It remaps the resolved "
        "`battery_temperature` (weather, fixed or CSV) to an indoor battery temperature. Omitting the table applies "
        "it with the defaults.",
    ),
    (
        "pv_arrays",
        PV_ARRAY_TABLE,
        "One entry per array, as `[[pv_arrays]]` in TOML. `modules` is required; an array inherits each other "
        "key it omits from the top level. See [Multi-array PV systems](configuration.md#multi-array-pv-systems).",
    ),
    (
        "tariff",
        TARIFF_TABLE,
        "Time-of-use prices, as `[tariff]` in TOML; see [Time-of-use tariffs](configuration.md#time-of-use-tariffs).",
    ),
    (
        "reference_tariff",
        REFERENCE_TARIFF_TABLE,
        "What the household would pay without the system, as `[reference_tariff]` in TOML; see "
        "[No-system reference tariff](configuration.md#no-system-reference-tariff). It prices the whole household "
        "load and its own fixed charge for the no-system cost, and nothing else: no export, and no effect on the "
        "dispatch. Without a `schedule` or `custom_schedule` it is one flat price, `import_prices = { all = <price> }`.",
    ),
    (
        "terminal_value",
        TERMINAL_VALUE_TABLE,
        "Optional estimated residual value of the final battery pack, as `[terminal_value]` in TOML. `basis` "
        'defaults to `"none"`; see [Estimated battery residual value](configuration.md#estimated-battery-residual-value).',
    ),
    (
        "smart_charging",
        SMART_CHARGING_TABLE,
        "Battery dispatch by tariff period, as `[smart_charging]` in TOML; see "
        '[Smart charging](configuration.md#smart-charging). `mode = "fixed_target"` needs '
        "`target_usable_fraction`, `charge_periods`, `discharge_periods` and `grid_charge_efficiency`, and refuses "
        'the planner keys. The experimental `mode = "daily_persistence"` (App only) needs the same keys but '
        "`target_usable_fraction`, which it refuses, and takes the optional planner keys `forecast_horizon_days`, "
        '`target_levels` and `soc_states`. `grid_import_limit_w` is optional in both. `mode = "discharge_only"` '
        "takes `discharge_periods` alone and refuses every grid-charging and planner key: it never charges from "
        'the grid. `mode = "disabled"` takes no other key. `overlap_policy` defaults to `"reject"`; '
        '`"hold_target"` permits overlapping periods for `fixed_target` only, retaining the target as the discharge floor.',
    ),
    (
        "period",
        PERIOD_TABLE,
        "A window shorter than a year, as `[period]` in TOML; see "
        "[Simulate part of a year](configuration.md#simulate-part-of-a-year). Both dates are local civil dates in the "
        "location's timezone, in the year of `start_date`, and the window runs from local midnight of `start` to "
        "local midnight of `end`.",
    ),
)

# Keys a table's own validator requires, where adding them to the spec's
# ``required`` would change the error a missing key raises.
_ALSO_REQUIRED = {"pv_arrays": frozenset({"modules"})}
_CONDITIONALLY_REQUIRED = {
    "tariff": {
        "schedule": "exactly one of these",
        "custom_schedule": "exactly one of these",
    },
    "smart_charging": {
        "charge_periods": "`fixed_target`, `daily_persistence`",
        "discharge_periods": "unless `disabled`",
        "grid_charge_efficiency": "`fixed_target`, `daily_persistence`",
        "target_usable_fraction": "`fixed_target`",
    },
}

_COST_PARAM_DEFAULTS = {field.name: field.default for field in fields(CostParams)}


def _literal(value: Any) -> str:
    text = json.dumps(value) if isinstance(value, str) else repr(value)
    return f"`{text}`"


def _checked(where: str, text: str) -> str:
    if not text.strip():
        raise ValueError(f"{where} has no doc text; add it to the config registry")
    if "|" in text or "\n" in text:
        raise ValueError(f"{where} doc text must be one line without '|'")
    return text


def _table(header: tuple[str, ...], rows: list[tuple[str, ...]]) -> str:
    for row in rows:
        for cell in row:
            if "|" in cell or "\n" in cell:
                raise ValueError(f"Table cell {cell!r} must be one line without '|'")
    lines = ["| " + " | ".join(header) + " |", "|" + "|".join("---" for _ in header) + "|"]
    lines.extend("| " + " | ".join(row) + " |" for row in rows)
    return "\n".join(lines)


def _top_level_rows() -> list[tuple[str, ...]]:
    rows = []
    for name in sorted(APP_CONFIG_FIELDS):
        field = APP_CONFIG_FIELDS[name]
        description = _checked(name, field.doc)
        if field.cli_choices:
            description += ". One of " + ", ".join(_literal(choice) for choice in field.cli_choices)
        if field.default_doc is not None:
            default = field.default_doc
        elif field.has_default:
            default = _literal(field.default)
        else:
            raise ValueError(f"{name} has neither a default nor default_doc")
        flags = ", ".join(f"`{flag}`" for flag in field.cli_flags) or "—"
        rows.append((f"`{name}`", default, flags, description))
    return rows


def _nested_rows(spec: TableSpec, name: str) -> tuple[tuple[str, ...], list[tuple[str, ...]]]:
    undocumented = sorted(set(spec.keys) - set(spec.docs))
    stray = sorted(set(spec.docs) - set(spec.keys))
    if undocumented or stray:
        raise ValueError(f"{name}: keys without docs {undocumented}, docs without keys {stray}")
    if spec is COSTS_TABLE:
        header = ("Key", "Default", "Description")
        rows = [
            (f"`{key}`", _literal(_COST_PARAM_DEFAULTS[COST_CONFIG_KEY_TO_PARAM[key]]), _checked(key, doc))
            for key, doc in sorted(spec.docs.items())
        ]
        return header, rows
    header = ("Key", "Required", "Description")
    always_required = spec.required | _ALSO_REQUIRED.get(name, frozenset())
    conditional_required = _CONDITIONALLY_REQUIRED.get(name, {})
    required = always_required | frozenset(conditional_required)
    keys = sorted(spec.keys, key=lambda key: (key not in required, key))
    rows = [
        (
            f"`{key}`",
            conditional_required.get(key, "yes" if key in always_required else ""),
            _checked(key, spec.docs[key]),
        )
        for key in keys
    ]
    return header, rows


def generate() -> str:
    sectioned = {id(spec) for _, spec, _ in TABLES}
    specs = [
        *NESTED_TABLE_SPECS.values(),
        *(value for value in vars(app_config).values() if isinstance(value, TableSpec)),
    ]
    missing = sorted({spec.name for spec in specs if id(spec) not in sectioned})
    if missing:
        raise ValueError(f"Tables {missing} have no section; add them to TABLES")
    parts = [
        HEADER,
        f"## Top-level keys\n\n{TOP_LEVEL_INTRO}\n"
        + _table(("Key", "Default", "CLI flag", "Description"), _top_level_rows())
        + "\n",
    ]
    for name, spec, intro in TABLES:
        header, rows = _nested_rows(spec, name)
        parts.append(f"## {name}\n\n{intro}\n\n{_table(header, rows)}\n")
    return "\n".join(parts)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if the committed page differs from the generated content.",
    )
    args = parser.parse_args(argv)

    content = generate()
    if args.check:
        committed = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else ""
        if committed != content:
            print(
                f"{OUTPUT_PATH.relative_to(REPO_ROOT)} is out of date with the config registry."
                " Run: uv run python tools/generate_config_docs.py",
                file=sys.stderr,
            )
            return 1
        print(f"{OUTPUT_PATH.relative_to(REPO_ROOT)} is up to date.")
        return 0

    OUTPUT_PATH.write_text(content, encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
