"""Generate docs/getting-started/options.md from packaged data and source constants.

The page is built from the same loader the ``breos list`` CLI uses, so the
documented tables cannot drift from ``breos/data/configs/*.json``,
``breos.pv_modules.MODULES``, and ``breos.load_profiles.PROFILE_NAMES``.

Regenerate after changing any of those sources:

    uv run python tools/generate_option_docs.py

CI runs this with ``--check`` and fails when the committed page is stale.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

from breos.cli import _load_options

REPO_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = REPO_ROOT / "docs" / "getting-started" / "options.md"

HEADER = """\
<!-- Generated by tools/generate_option_docs.py. Do not edit by hand. -->

# Packaged options

The option keys accepted by {py:class}`~breos.App` config dicts, generated
from the packaged data files and source constants. The same lists are
available at the command line via `breos list <category>` (add `--json` for
machine-readable output).

Packaged presets exist to make BREOS runnable out of the box. For a real
study, review [Required Inputs](inputs.md) and replace the assumptions that
matter to your project.
"""

SECTIONS: list[dict[str, Any]] = [
    {
        "category": "locations",
        "title": "Locations",
        "intro": (
            "Preset keys for the `location` config key, from"
            " `breos/data/configs/locations.json`. Any other site works with a"
            " coordinate dict — see [Recipes](recipes.md)."
        ),
        "columns": [
            ("key", "Key", "code"),
            ("name", "Name", "text"),
            ("latitude", "Latitude", "text"),
            ("longitude", "Longitude", "text"),
            ("timezone", "Timezone", "code"),
        ],
    },
    {
        "category": "modules",
        "title": "PV modules",
        "intro": "Catalogue keys for the `pv_module` config key, from `breos.pv_modules.MODULES`.",
        "columns": [
            ("key", "Key", "code"),
            ("power_w", "Power (W)", "text"),
            ("name", "Name", "text"),
            ("celltype", "Cell type", "text"),
        ],
    },
    {
        "category": "cost-presets",
        "title": "Cost presets",
        "intro": (
            "Preset keys for the `cost_preset` config key, from"
            " `breos/data/configs/costs.json`. Editable copies live in `configs/base/`."
        ),
        "columns": [
            ("key", "Key", "code"),
            ("electricity_cost_eur_kwh", "Buy (EUR/kWh)", "text"),
            ("export_price_eur_kwh", "Export (EUR/kWh)", "text"),
            ("storage_cost_eur_kwh", "Battery (EUR/kWh)", "text"),
        ],
    },
    {
        "category": "emissions",
        "title": "Emissions factors",
        "intro": ("Country codes for the `emissions_country` config key, from `breos/data/configs/emissions.json`."),
        "columns": [
            ("key", "Key", "code"),
            ("country", "Country", "text"),
            ("grid_intensity_gco2_kwh", "Grid intensity (gCO2/kWh)", "text"),
            ("year", "Year", "text"),
        ],
    },
    {
        "category": "load-profiles",
        "title": "Load profiles",
        "intro": (
            "Keys for the `load_profile` config key, from"
            " `breos.load_profiles.PROFILE_NAMES`. Non-bundled profiles need their"
            " source CSVs supplied through `rlp_directory` — see"
            " [Load Profile Data](../legal/load-profile-data.md) for expected"
            " filenames and licensing notes."
        ),
        "columns": [
            ("key", "Key", "code"),
            ("name", "Name", "text"),
            ("bundled", "Bundled", "text"),
        ],
    },
]


def _cell(value: Any, style: str) -> str:
    if value is None:
        return "—"
    if isinstance(value, bool):
        return "yes" if value else "no"
    text = str(value)
    return f"`{text}`" if style == "code" else text


def _table(rows: list[dict[str, Any]], columns: list[tuple[str, str, str]]) -> str:
    lines = [
        "| " + " | ".join(header for _, header, _ in columns) + " |",
        "|" + "|".join("---" for _ in columns) + "|",
    ]
    for row in rows:
        lines.append("| " + " | ".join(_cell(row[field], style) for field, _, style in columns) + " |")
    return "\n".join(lines)


def generate() -> str:
    parts = [HEADER]
    for section in SECTIONS:
        rows = _load_options(section["category"])
        parts.append(f"## {section['title']}\n\n{section['intro']}\n\n{_table(rows, section['columns'])}\n")
    return "\n".join(parts)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if the committed page differs from the generated content.",
    )
    args = parser.parse_args(argv)

    content = generate()
    if args.check:
        committed = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else ""
        if committed != content:
            print(
                f"{OUTPUT_PATH.relative_to(REPO_ROOT)} is out of date with the packaged data."
                " Run: uv run python tools/generate_option_docs.py",
                file=sys.stderr,
            )
            return 1
        print(f"{OUTPUT_PATH.relative_to(REPO_ROOT)} is up to date.")
        return 0

    OUTPUT_PATH.write_text(content, encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
